### ISSUE TITLE
Changed the default /pl perms

### ISSUE THREAD

**Issue by diamkil** [SupremeObsidian/ProjectManager#130]
Denied the default group access to it (have access by default) and added the perms to the base staff groups (artist, builder, developer, configurator, helper, forum-manager, recruitment-manager) they had access before but since I denied it on the default group it denied for them do

TLDR: Removed /pl perms for default, gave it back to every staff

**Comment by violetskyzz** [comment]
I cant link this to the system admin project, but yeaaaaaa @UUBlueFire

**Comment by UUBlueFire** [comment]
Documentation updated

**Comment by dryter97** [comment]
The goal was to change the command not to deny permission acces. Anyway
glad this is done
