### ISSUE TITLE
Blockstate updates in temp-paste

### ISSUE THREAD

**Issue by EmanuelSimard** [SupremeObsidian/ProjectManager#142]
Context:
I accepted a side quest and followed the side quest arrow. When I arrived at the side quest chunk and completed the side quest, the chunk reverted back to a corner beach with rocks/corals. 
https://imgur.com/6R6S9tQ

Problem:
However the corals now had water in them.
https://imgur.com/B8YbiKf

Possible Solution:
Side quests shouldn't spawn on beaches or forest edges. If we decided they should,  then we would need to make sure the schematic that gets reverted doesn't flood with watered corals.

**Comment by violetskyzz** [comment]
Fixed
