### ISSUE TITLE
Fix Oxeye Daisy bug 

### ISSUE THREAD

**Issue by chloexburman** [SupremeObsidian/ProjectManager#15]
Fix broken texture on Oxeye Daisy.

**Comment by UUBlueFire** [comment]
![Capture](https://user-images.githubusercontent.com/34107923/99965941-e462f680-2d95-11eb-8332-d2a30089515e.PNG)

The Oxeye Daisy has a broken texture depending on its location in the world

**Comment by UUBlueFire** [comment]
Textures updated
