### ISSUE TITLE
Change memory settings for Hayden's servers

### ISSUE THREAD

**Issue by UUBlueFire** [SupremeObsidian/ProjectManager#150]
- [x] Lobby 2GB
- [x] SMP 3GB
- [x] KitPvP 3GB
- [x] Minigames 3GB
- [x] Bungee 2GB
- [ ] Skyblock (create new server) 3GB

**Comment by lowexer** [comment]
please make sure its paper 1.16.x

**Comment by UUBlueFire** [comment]
> please make sure its paper 1.16.x

I've updated the memory settings and created the skyblock server. The server has been set to paper. However you might have to upload your own server.jar file
