### ISSUE TITLE
Haydens server prefrences

### ISSUE THREAD

**Issue by lowexer** [SupremeObsidian/ProjectManager#153]
Id like to go from 16 to 32 gigs a month at 2.55$ a gig for 82$ USD paid to kalinox starting on january 5th 

Preferred allocations as follows, 

- [x] Bungee: 2Gb
- [x] Lobby: 2
- [x] Towny: 8
- [x] Kitpvp:6
- [x] Minigames:6
- [x] Skyblock: 8

please shoot me a dm on discord when the task is in progress ill be looking out for the message if you have any questions please feel free to ask 
thanks, 
Hayden (lowexer)

**Comment by UUBlueFire** [comment]
Server Memory allocations have been changed
