### ISSUE TITLE
We need to change the welcome bot picture to say welcome to Ethera

### ISSUE THREAD

**Issue by EmanuelSimard** [SupremeObsidian/ProjectManager#199]

**Comment by UUBlueFire** [comment]
![WelcomeBack](https://user-images.githubusercontent.com/34107923/104090821-72793a80-5279-11eb-80b3-a9ae1afe16f0.png)
![Welcome](https://user-images.githubusercontent.com/34107923/104090823-7311d100-5279-11eb-87ac-6f1aabd89302.png)

@violetskyzz Could you please Modify these images to represent Ethera? Make sure the size and position of the avatar box is the same as the old images.
