### ISSUE TITLE
Schemy messing with maps and entities

### ISSUE THREAD

**Issue by LeoCx1000** [SupremeObsidian/ProjectManager#272]
**Describe the bug**
Schemy does not properly save maps or other entities. (_it also seems to hate pickles_)

**To Reproduce**
1) Open a schemy.
2) place a map. (or other entities.
3) Draft your schemy and leave
4) Re-open your schemy

**Expected behavior**
Your paintings are the same, nothing changed

**Observed behavior**
Paintings are all rotated wrongly, or destroyed. They'll all be all facing west (i think)

**Comment by violetskyzz** [comment]
World edit issue. Resolved
